name: Selenium Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Test with Maven
      run: mvn test
      continue-on-error: true

    - name: Generate HTML REPORT FROM SUREFIRE_REPORTS
      run: mvn surefire-report:report
      if : always()
    - uses: actions/upload-artifact@main
      with:
        name: HTML-REPORT
        path: target/site/surefire-report.html

  
